### ISSUE TITLE
Cannot contribute on Windows

### ISSUE THREAD

**Issue by BryanCrotaz** [achambers/ember-cli-deploy-original#76]
```
F:\Projects\ember-cli-deploy>npm install
npm ERR! Failed to clone git+https://github.com/chjj/pty.js#18238d37e2915b3ac97e
4ae0d5cb3e33f76ac758 from https://github.com/chjj/pty.js fatal: could not create
 work tree dir 'c:\WINDOW~1\npm-596-0a11d7a5\1421283827369-0.7769959352444857\18
238d37e2915b3ac97e4ae0d5cb3e33f76ac758'.: No such file or directory
npm ERR! Failed to clone git+https://github.com/chjj/pty.js#18238d37e2915b3ac97e
4ae0d5cb3e33f76ac758 from https://github.com/chjj/pty.js
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code 128
```

**Comment by BryanCrotaz** [comment]
can't find any reference to chjj/pty - what's using it?

**Comment by srsgores** [comment]
Same here:

> Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.
> C:\Users_admin\Documents\GitHub\seangoresht>npm install --save-dev ember-cli-deploy
> \
> pty.js@0.2.4 install C:\Users_admin\Documents\GitHub\seangoresht\node_modules\ember-cli-deploy\node_modules\ember-cli-deploy-redis-index-adapter\node
> _modules\gitty\node_modules\pty.js
> node-gyp rebuild
> C:\Users_admin\Documents\GitHub\seangoresht\node_modules\ember-cli-deploy\node_modules\ember-cli-deploy-redis-index-adapter\node_modules\gitty\node_mod
> ules\pty.js>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
> gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users_admin\Documents\GitHub\seangoresht\node_modules\ember-cli-deploy\node_modules\ember-cli-deploy-red
> is-index-adapter\node_modules\gitty\node_modules\pty.js) while loading dependencies of binding.gyp while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
> gyp ERR! System Windows_NT 6.2.9200
> gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users_admin\Documents\GitHub\seangoresht\node_modules\ember-cli-deploy\node_modules\ember-cli-deploy-redis-index-adapter\node_modules\g
> itty\node_modules\pty.js
> gyp ERR! node -v v0.10.33
> gyp ERR! node-gyp -v v1.0.1
> gyp ERR! not ok
> execSync@1.0.2 install C:\Users_admin\Documents\GitHub\seangoresht\node_modules\ember-cli-deploy\node_modules\ember-cli-deploy-redis-index-adapter\no
> de_modules\gitty\node_modules\execSync
> node install.js
> [execsync v1.0.2] Attempting to compile native extensions.
> { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
> [execSync v1.0.2]
>     Native code compile failed!!
>     Will try to use win32 extension.
> npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the pty.js@0.2.4 install script.
> npm ERR! This is most likely a problem with the pty.js package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls pty.js
> npm ERR! There is likely additional logging output above.
> npm ERR! System Windows_NT 6.2.9200
> npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--save-dev" "ember-c
> li-deploy"
> npm ERR! cwd C:\Users_admin\Documents\GitHub\seangoresht
> npm ERR! node -v v0.10.33
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm ERR! not ok code 0

Windows 8.1 x64

Please consider fixing.

**Comment by achambers** [comment]
Yep, this hasn't been developed to support Windows as yet.  Feel free to submit a PR.

**Comment by BryanCrotaz** [comment]
Looks as though pty needs replacing with something windows compliant - where is pty used?

**Comment by achambers** [comment]
`ember-cli-deploy` is in the process of merging with `ember-deploy`.  Therefore, no more changes will be made to this repo.  Please see [the README](https://github.com/achambers/ember-cli-deploy#breaking-news) for more details. /cc @Twinkletoes @srsgores
